### ISSUE TITLE
Step 5 - NFT Transfer, Test and Display page

### ISSUE THREAD

**Issue by Redoudou** [ChainSafe/filecoindot#154]
The user reach to a the page where they can carry out several actions.

5.1. list all the existing NFT associated to that address
5.2 enter another polkadot address and transfer the NFT. No need to capture errors.
5.3 test another CID >> cf #148

![image.png](https://images.zenhubusercontent.com/583c166cb9dc3c622022967a/a87aefbb-09b2-4dab-b0e1-5bc2c1a36a5a)

**Comment by Tbaut** [comment]
A couple comments:
- We won't connect to rococo, because it doesn't have the filecoindot pallet. The connection will be by default to a local substrate node, where the filecoindot pallet is expected to be.
- As of now, there is no logic in the pallet to list all the NFTs for an account. Showing this in the UI would require an external explorer service, or this ability in the nft pallet.

**Comment by Redoudou** [comment]
@Tbaut 
After review with the client we got their verbal agreements that the listing of existing NFT won't be required as an acceptance criteria.
